# Generated by Django 4.2.3 on 2023-08-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='amount',
        ),
    ]
